# Generated by Django 3.2.12 on 2023-01-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='data_atendimento',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='status_atendimento',
            field=models.CharField(default='fila', max_length=255),
        ),
    ]
