# Generated by Django 4.1.4 on 2023-03-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0010_alter_atendimento_data_fim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='data_inicio',
        ),
    ]
