# Generated by Django 4.1.4 on 2023-03-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0011_remove_atendimento_data_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='data_fim',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='data_inicio',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
