# Generated by Django 4.1.4 on 2023-03-24 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0007_atendente_registrador'),
        ('atendimento', '0012_atendimento_data_fim_atendimento_data_inicio'),
    ]

    operations = [
    ]
