# Generated by Django 4.1.4 on 2023-03-24 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabine', models.CharField(max_length=100)),
                ('registrador', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixo', models.CharField(max_length=4)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Digite seu nome')),
                ('data_atendimento', models.DateTimeField(auto_now_add=True)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('status_atendimento', models.CharField(default='fila', max_length=255)),
                ('numero_senha', models.IntegerField()),
                ('atendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='atendimento.atendente')),
                ('tipo_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atendimento.tipoatendimento')),
            ],
        ),
        migrations.AddField(
            model_name='atendente',
            name='tipo_atendimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atendimento.tipoatendimento'),
        ),
        migrations.AddField(
            model_name='atendente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
