# Generated by Django 4.2.5 on 2024-02-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendente',
            name='tipo_atendimento',
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='data_fim',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='data_inicio',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='atendente',
            name='tipo_atendimento',
            field=models.ManyToManyField(to='atendimento.tipoatendimento', verbose_name='Tipo'),
        ),
    ]
