# Generated by Django 4.1.4 on 2023-01-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0002_auto_20230129_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='nome_cliente',
            field=models.CharField(max_length=255, verbose_name='Digite seu nome'),
        ),
        migrations.AlterField(
            model_name='tipoatendimento',
            name='prefixo',
            field=models.CharField(max_length=4),
        ),
    ]
