# Generated by Django 4.1.4 on 2023-01-31 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0003_alter_atendimento_nome_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendente',
            name='tipo_atendimento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='atendimento.tipoatendimento'),
            preserve_default=False,
        ),
    ]
