# Generated by Django 4.1.4 on 2023-02-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0004_atendente_tipo_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='nome_cliente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Digite seu nome'),
        ),
    ]
