# Generated by Django 4.1.4 on 2023-03-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0006_alter_atendimento_data_atendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendente',
            name='registrador',
            field=models.BooleanField(default=False),
        ),
    ]
