# Generated by Django 4.1.4 on 2023-03-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0006_alter_atendimento_data_atendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='data_fim',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='data_inicio',
            field=models.DateTimeField(default=None),
        ),
    ]
