# Generated by Django 4.1.4 on 2023-03-20 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0007_atendimento_data_fim_atendimento_data_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='data_fim',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 10, 42, 1, 500377)),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='data_inicio',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 10, 42, 1, 500377)),
        ),
    ]
