# Generated by Django 4.1.4 on 2023-03-20 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0009_alter_atendimento_data_fim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='data_fim',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='data_inicio',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
    ]
