# Generated by Django 4.1.4 on 2023-03-20 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0012_atendimento_data_fim_atendimento_data_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='data_inicio',
        ),
    ]
